### ISSUE TITLE
🐛 [Bug]Feign Death is ineffective

### ISSUE THREAD

**Issue by ctmwow** [Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8#280] opened 2024-07-16 18:49 UTC
When using feign death, character movement will not cancel the feign death aura and state;
If feign death is used in combat, the feign death aura and status will be automatically cancelled.

**Comment by jasongdove** [comment] 2024-07-17 19:00
> character movement will not cancel the feign death aura and state;

This should be fixed with #281 

> If feign death is used in combat, the feign death aura and status will be automatically cancelled.

I'm not familiar with Hunter behavior; it looks like you have to manually stop attacking before casting feign death for it to work on the current build. Is that behavior incorrect?

**Comment by ctmwow** [comment] 2024-07-23 15:28
Find a training dummy, attack it to enter in combat, and then cast Feign Death, You will find that the character automatically stands up and continues shooting at the target.

**Comment by jasongdove** [comment] 2024-07-24 21:19
The `SMSG_CANCEL_AUTO_REPEAT` packet is wrong, and there are other things that should be improved with auto repeat. I will fix.

**Comment by jasongdove** [comment] 2024-10-05 11:46
Looks like the problem is actually `SMSG_CANCEL_COMBAT`. It might be fixed with an update to https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/pull/356

**Closed** 2024-10-07 10:08 UTC
Labels: bug
